### ISSUE TITLE
crash with unhandled entity type 7

### ISSUE THREAD

**Issue by BenCastricum** [rpki-client/rpki-client-portable#76] opened 2022-11-30 08:55 UTC
Starting 29th of Nov at 13:00 CET our dockerized rpki-client no longer produces any files.

Docker logging:

```
2022-11-30T08:30:50.064813443Z rpki-client: rpki-rps.arin.net/repository/8a848ade7fb71aa9017fdd9c5dd324c7/0/EB1DD8AA3E2B6864E06379C751DBFFFCC6418350.mft: no valid mft available
2022-11-30T08:30:50.100377723Z rpki-client: rpki-rps.arin.net/repository/8a848ade7fb71aa901800003287f4402/0/2BF7605B8927C87448B3B294A8B61D8E983248E0.mft: no valid mft available
2022-11-30T08:30:50.287559589Z rpki-client: rpki-rps.arin.net/repository/8a848adf7fb722e9017ffead9f534ac5/0/BFA2750976CA07F56A68976B0F01EB862F17C3B3.mft: no valid mft available
2022-11-30T08:31:05.479810276Z rpki-client: unhandled entity type 7
2022-11-30T08:31:05.566212488Z rpki-client: poll[0]: bad fd
2022-11-30T08:31:05.566249456Z rpki-client: write[0]: Broken pipe
2022-11-30T08:31:05.566256810Z rpki-client: parser process exited abnormally
2022-11-30T08:31:05.571419260Z rpki-client: not all files processed, giving up
2022-11-30T08:31:05.966877368Z rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(713) [Receiver=3.2.4]
```
We are still using rpki-client 7.9
```
sudo docker inspect --format='{{index .RepoDigests 0}}' rpki/rpki-client:7.9
rpki/rpki-client@sha256:81f6c17b508e5184185a15e33f6f9f578d454ed6e78d67fa78c9182bf5f911ce
```

**Comment by cjeker** [comment] 2022-11-30 09:16
This problem has been fixed in the 8.0 release.
It was caused by improper handling of .asa files. It seems a CA added a .asa file triggering this bug.

**Comment by job** [comment] 2022-11-30 09:34
However 8.0 had this issue blocking some folks from using it https://github.com/rpki-client/rpki-client-openbsd/commit/ec0949ce76d706aa232c119d53258eeca197ff73

**Comment by cjeker** [comment] 2022-11-30 09:55
In that case a quick fix would be to downgrade to 7.8 until 8.1 is out. It does not have this problem with .asa files.

**Comment by robert-scheck** [comment] 2022-11-30 10:11
> However 8.0 had this issue blocking some folks from using it [rpki-client/rpki-client-openbsd@ec0949c](https://github.com/rpki-client/rpki-client-openbsd/commit/ec0949ce76d706aa232c119d53258eeca197ff73)

https://github.com/rpki-client/rpki-client-container/commit/a1eed1d6b27e874506e310848ba8384f947f0c57 was added to a re-tagged 8.0 container image (including a fixed `rsync`).

**Comment by BenCastricum** [comment] 2022-11-30 11:08
Thanks, we are running 7.8 and the latest 8.0 on our test environment at the moment. If no problems occur we will switch back to 7.8. We prefer a solid tag for a release, and 7.8 has already done some time in our production environment.

**Comment by cjeker** [comment] 2022-12-14 13:19
rpki-client 8.2 finally was released which has both the .asa file exception and the proxy port handling fixed.
So this should be solved for good now.

**Closed by cjeker** 2022-12-14 13:19 UTC
